name: Deploy Buenaventura Reporta

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Build del frontend
        env:
          CI: false
          GENERATE_SOURCEMAP: false
        run: npm run build

      - name: Preparar y Limpiar carpeta en Servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p /var/www/ds1/buenaventura-reporta/html
            # Limpia todo menos el .htaccess para no romper el ruteo de React/Vite
            find /var/www/ds1/buenaventura-reporta/html -mindepth 1 ! -name '.htaccess' -delete

      - name: Desplegar Build al VPS vía SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "dist/*"  
          target: "/var/www/ds1/buenaventura-reporta/html"
          strip_components: 1
          rm: false

      - name: Finalizar Despliegue
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Despliegue finalizado con éxito en el servidor"
